### ISSUE TITLE
使用bazel 當作build tool

### ISSUE THREAD

**Issue by HowJMay** [WasmVM/WasmVM#135]
關於之前提到使用bazel 當作build tool 不知道大家有什麼看法，所以開一個issue 討論

**Comment by oiz5201618** [comment]
有辦法比較 bazel 跟現在 build tool 的差別跟優點嗎？
因為沒使用過 bazel 希望能有個簡單的描述，
還是多一個工具對現在的系統來說是不衝突可以共存的？

**Comment by LuisHsu** [comment]
要考慮可否接上 SkyPat，SkyPat 是只有 automake
CMake 的話我是用自訂 command 的方式讓 CMake 可以編譯 SkyPat
bazel 如果也可以自訂 command 或用其他方式編譯 automake 的 project 的話，我是樂觀其成

還有 unittest 那邊也要能自動生出 .cpp 檔

如果能處理的話，剩下的就是看看 bazel 是否能真的讓編譯速度變快
因為 CMake 老實說真的蠻慢的
