### ISSUE TITLE
Runtime 裡 load, store 指令的位置＆檢查範圍不對 

### ISSUE THREAD

**Issue by LuisHsu** [WasmVM/WasmVM#164]
### 問題描述

1. 檢查範圍

規格裡寫到：

>  If ea + 𝑁/8 is larger than the length of mem.data, then:
>  (a) Trap.

但是目前只檢查 ea, 沒加上後面的 𝑁/8

2. `dataPointer` 先轉成對應的型別再加上 ea，會多跑很多 byte，位置不對

### 建議解決方法

1. 檢查 ea 時加上 𝑁/8 再做比較

2. 取得 `dataPointer` 時建議修改成以下步驟：

    *  `memory->data->data` 轉成 `uint8_t*`
    *  加上 ea
    *  轉成對應型別的指標

**Comment by yuhao-kuo** [comment]
## 已知 store 指令問題清單
[ ] i32_store
[ ] i32_store16
[ ] i32_store8
[ ] i64_store

**Comment by LuisHsu** [comment]
感謝大家，所有的問題都修完了！
👏
