### ISSUE TITLE
記憶體洩漏問題

### ISSUE THREAD

**Issue by Naetw** [WasmVM/WasmVM#170]
剛剛寫了腳本來測試目前有的程式碼，發現不少記憶體洩漏問題（像是 [WasmData 裡面的 init](https://github.com/WasmVM/WasmVM/blob/9be270b06e9e2b1fdf6875392ac411ef4b4d4a43/src/lib/structures/WasmData.c#L14) 應該要用 `free_vector` 去釋放記憶體空間），核心程式碼的部分正在修改中。

此外多數 unittest 也存在相同問題，但 unittest 的問題比較沒關係，畢竟不會影響正常程式運作，因此想詢問一下 unittest 的部分需要一併修正嗎？

**Comment by LuisHsu** [comment]
關於記憶體洩漏的問題
我本來是想說 release 1.0 要發出的時候再硬性要求，大家一起修一修
不過既然有人提了，目前能修就盡量修，之後會比較要求

**Comment by Naetw** [comment]
目前比較好處理的問題已解決（E.g., #171  #172 ）。

另外也發現一些跟設計上有關，比較複雜的問題：

- `WasmControlInstr` 需不需要實做自己的 new & free
  - 像是[這裡](https://github.com/WasmVM/WasmVM/blob/1cd0ef4b521bb23090e7c463395b6291e8ac5409/test/unittests/lib/validator/validate_Instr_Control_unittest.hpp#L72)使用到的 `WasmControlInstr` 物件，在後面用到 `new_vector` 來給它的成員，但在結尾部分只單純使用 `free` 來釋放 `WasmControlInstr` 物件本身
  - 若有自己的 new & free 應該會比較好處理
- `FuncType` 跟 `WasmModule` 的交互使用問題
  - 問題出現在 [`SKYPAT_F(Validate_Instr_br_if, index_out_of_range`)
](https://github.com/WasmVM/WasmVM/blob/1cd0ef4b521bb23090e7c463395b6291e8ac5409/test/unittests/lib/validator/validate_Instr_Control_unittest.hpp#L725)
  - `FuncType` 自身建構物件時就會使用到 `new_vector` 來初始化，但是在上面提到的單元測試中跟 module 間的互動是 module 會 `push_back` `FuncType` 物件，由於 `push_back` 是複製資料過去，它會把 `FuncType` 物件 new 出來的指標也一併複製過去，如此一來在處理 `FuncType` 物件的生存時間複雜性就提高了，因為必須要等 module 用完才能夠釋放空間
  - 這邊可能要再討論要怎麼做：
    - 照舊有的設計處理
    - 修改舊有的設計

**Comment by LuisHsu** [comment]
1. WasmControlInstr 有自己的 new 和 free 不錯，因為他已經有用到 vector 這個衍生的 type

2. 載入時 `FuncType` 存在 WasmModule，他們本來就同進退
    
    執行時 `FuncType` 的資訊不像 function, table, memory, global 一樣抽離到 Store ，而是繼續存在 ModuleInst，所以和 module 一樣是同進退的。

    所以 FuncType 跟 WasmModule 他們在使用上都是同進退，必須等 module 用完才能夠釋放空間這件事是沒有問題，而且應該發生的，只是在 unittest 的時候為了測試才會單獨使用而已。

**Comment by Naetw** [comment]
了解！

目前已修完：

- 簡易的核心程式部分
  - stack
  - FuncInst
  - WasmData
  - InstrValidates
  - vector
- runtime 的 unittest

剩下幾個 validator unittest, loader 跟上面提到的那兩個，loader 部分也有比較複雜的問題，晚點整理後會再提出。

**Comment by Naetw** [comment]
研究 Loader 後目前有以下問題：

- queue, list 沒有單元測試
- [`free_queue`](https://github.com/WasmVM/WasmVM/blob/1cd0ef4b521bb23090e7c463395b6291e8ac5409/src/lib/dataTypes/queue.c#L59) 可能要稍微設計一下
  - 因為 queue 在 push 時會自己 `malloc` 一塊節點，因此不管 `freeElem` 是不是 NULL 都應該要走訪整個 queue 來釋放節點空間
  - 這邊目前有兩個想法
    - 用 if, else 來寫兩個區塊，兩個差異只有一個有呼叫 `freeElem` 另一個沒有
    - 實做一個什麼都不做的函式，當初始化時參數 `freeElem` 傳入 NULL 時就使用，這樣一來就不需要用 if, else 區分

**Comment by Naetw** [comment]
嗯嗯，同意。看到 #72 所以想說之後再處理，目前 stack 的做法就是維持跟 queue 一樣。

**Comment by LuisHsu** [comment]
之前抓掉了 vector at 的問題，但是 vector 的 free 只會釋放整塊記憶體，沒法釋放各個元素

**Comment by Naetw** [comment]
vector 的 push 是直接複製資料上去應該不需要釋放各個元素？

**Comment by Naetw** [comment]
上次的討論是說「freeElem 只有當 vector 的元素為 malloc 出來的 pointer address 之類的才需要使用到」，所以最後決定棄用 freeElem 單純釋放 data 這塊記憶體就好，之前送 pr 時忘記把 header 裡的 freeElem 拔掉了 @@

**Comment by LuisHsu** [comment]
抱歉我上面講的不夠精確，的確是不需要釋放各個元素
但是如果 vector 裡存的物件有包含指標，在釋放前需要先呼叫每個物件的 clean function 清理他自己的指標

**Comment by Naetw** [comment]
嗯嗯瞭解！那跟上次討論的差不多 XD

**Comment by LuisHsu** [comment]
#177
