### ISSUE TITLE
i32_popcnt 算術指令BUG

### ISSUE THREAD

**Issue by YanJiunhaha** [WasmVM/WasmVM#185]
https://github.com/WasmVM/WasmVM/blob/f702cac97bc859bce34735f9adfd70d8e0ccd3f9/src/lib/core/runtime/i32_popcnt.c#L10-L17
#L10 這裡 value 如果使用 int32_t 型態，會使後面 #L16 運算有問題。

由於這裡 value 型態為**有號數**，將使用*算數位移*。
*算術位移*與*邏輯位移*最大的差別在於，*算術位移*會**考慮數值的正負號**。
因此這裡 value 如果為負值，將會進入死迴圈。

**Comment by YanJiunhaha** [comment]
剛剛查了一下[C99規格書](http://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf)。
6.5.7 Bitwise shift operators 上寫道：
The result of E1 >> E2 is E1 right-shifted E2 bit positions. If E1 has an unsigned type
or if E1 has a signed type and a nonnegative value, the value of the result is the integral
part of the quotient of E1 divided by the quantity, 2 raised to the power E2. If E1 has a
signed type and a negative value, **the resulting value is implementation-defined**.

會不會是我的編譯器實作不一樣？

**Comment by LuisHsu** [comment]
的確這邊需要考慮有號數的問題，所以加個 unsigned 比較妥當
