### ISSUE TITLE
dataType naming with suffix _t

### ISSUE THREAD

**Issue by HowJMay** [WasmVM/WasmVM#193]
To make dataTypes and variables naming more flexible, should we add suffix _t?
i.e. from `stack` to `stack_t`, from `ModuleInst` to `ModduleInst_t`

**Comment by yuhao-kuo** [comment]
將 suffix 使用在基本的 `type` / `structure` 中，用這個方式來區分基本的 `type` / `structure` 和 WasmVM `元件` 也許會比較直觀。

**Comment by HowJMay** [comment]
要改嗎？

**Comment by YanJiunhaha** [comment]
我覺得可以改，我剛開始加入的時候，閱讀程式碼也很容易搞混。

**Comment by LuisHsu** [comment]
我覺得OK，各個大寫開頭的  structure 會保留大寫，不過小寫開頭的像  queue, vector, stack 之類的會加 suffix

**Comment by LuisHsu** [comment]
我在整裡的時候發現用 _t 會和 OS 裡的 stack_t 撞到，所以改用  _p

**Comment by LuisHsu** [comment]
#222
