### ISSUE TITLE
List removeAt size大小錯誤及tail問題

### ISSUE THREAD

**Issue by yuhao-kuo** [WasmVM/WasmVM#202]
### size 大小
釋放了 `index` 位置的物件後，`list` 中的 `size` 數值不會改變。

### tail 釋放
`list` 中資料僅剩下 **1筆** 時，`removeAt` 將其移除後，`tail` 指標並不會被清空。
當資料再次透過 `push_back` 加入 `list` 時，會因 `push_back` 檢查 `tail` 來進行資料串接，導致新產生的 node 遺失。
```c
/* listPushBack in list.c */
if(thislist->tail != NULL) {
    thislist->tail->next = newNode;
} else {
    thislist->head = newNode;
}
```

**Comment by LuisHsu** [comment]
嗯.....的確有這個問題
我只有處理 head，忘記處理 Tail

**Comment by LuisHsu** [comment]
還好目前沒有 code 用到 list 的 removeAt
有興趣的人直接改完發 PR 就好

**Comment by LuisHsu** [comment]
剛剛按錯

**Comment by yuhao-kuo** [comment]
@LuisHsu 那我直接放到 #184 一起修正囉
