### ISSUE TITLE
[tutorial] wasmvm-tutorial/build 錯誤更正

### ISSUE THREAD

**Issue by Nienzu** [WasmVM/WasmVM#82]
[教學連結](https://luishsu.gitbook.io/wasmvm-tutorial/build) git clone 部分

```
git clone git@github.com:LuisHsu/WasmVM.git
```
是否要更改為?

```
git clone git@github.com:WasmVM/WasmVM.git
```

**Comment by LuisHsu** [comment]
嗯嗯，應該是要改一下

**Comment by Nienzu** [comment]
環境安裝
```
sudo apt install git cmake binutil
```
binutil 應修正為 binutils

**Comment by LuisHsu** [comment]
@jkrvivian 有發 PR 修改，我看一下
https://github.com/WasmVM/Tutorial/pull/1

**Comment by Nienzu** [comment]
原來 gitbook 可以直接從 github repo 來發布，學到了！
另外，那個 PR 是有用的，剛剛我有試過了！

**Comment by LuisHsu** [comment]
在 gitbook 可以和 GitHub 做連結，這樣就會連動
