### ISSUE TITLE
coding style 規範與檢查工具討論

### ISSUE THREAD

**Issue by jkrvivian** [WasmVM/WasmVM#93]
越來越多人投入，我們應該規範程式碼 coding style，以維持程式碼的一致性。
先前 @kevinbird61 已提出可以使用
* coding style
    * K&R
* 工具
     * astyle 

同時透過 git hook 確保提交者能維持一致的 coding style
參考範例：https://github.com/embedded2015/prefetcher/tree/master/scripts

@LuisHsu  @kevinbird61

**Comment by kevinbird61** [comment]
LGTM @jkrvivian  @LuisHsu 
我覺得這項 coding style 維持可以加入 githook 當中
就不需要在每次 commit 前手動 format.

**Comment by LuisHsu** [comment]
感覺不錯！這部份就由 @jkvivian 和 @kevinbird61 規劃規劃

**Comment by kevinbird61** [comment]
目前已經加上，可以參考 #98

**Comment by LuisHsu** [comment]
已 merge，關囉！
